package com.portsight.api.domains.reporting.service;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Map;

@Component
public class PdfReportBuilder {

    private static final Logger log = LoggerFactory.getLogger(PdfReportBuilder.class);

    private static final DeviceRgb PRIMARY = new DeviceRgb(0, 85, 255);
    private static final DeviceRgb HEADER_BG = new DeviceRgb(0, 85, 255);
    private static final DeviceRgb ROW_ALT = new DeviceRgb(245, 247, 250);
    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm")
            .withZone(ZoneId.systemDefault());

    /**
     * Generate a PDF report byte array.
     *
     * @param reportType    PORTFOLIO / RISK / PERFORMANCE / ALLOCATION
     * @param data          map of label -> value pairs to render in the report
     * @param portfolioName name of the portfolio
     */
    public byte[] generate(String reportType, String portfolioName, Map<String, String> data) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfWriter writer = new PdfWriter(baos);
            PdfDocument pdf = new PdfDocument(writer);
            Document doc = new Document(pdf);

            doc.setMargins(50, 50, 50, 50);

            // ── Header bar ────────────────────────────────────────────────────
            Table header = new Table(UnitValue.createPercentArray(new float[] { 1 }))
                    .useAllAvailableWidth()
                    .setBackgroundColor(HEADER_BG)
                    .setMarginBottom(20);

            Cell headerCell = new Cell()
                    .setBorder(null)
                    .setPadding(16)
                    .add(new Paragraph("PortSight Analytics")
                            .setFontColor(ColorConstants.WHITE)
                            .setFontSize(18)
                            .setBold())
                    .add(new Paragraph(formatReportTitle(reportType) + " Report")
                            .setFontColor(ColorConstants.WHITE)
                            .setFontSize(12));
            header.addCell(headerCell);
            doc.add(header);

            // ── Meta info ─────────────────────────────────────────────────────
            doc.add(new Paragraph("Portfolio: " + portfolioName)
                    .setFontSize(11)
                    .setBold()
                    .setFontColor(new DeviceRgb(30, 40, 60)));

            doc.add(new Paragraph("Generated: " + FMT.format(Instant.now()))
                    .setFontSize(9)
                    .setFontColor(new DeviceRgb(120, 130, 150))
                    .setMarginBottom(20));

            // ── Section title ─────────────────────────────────────────────────
            doc.add(new Paragraph(formatReportTitle(reportType) + " Summary")
                    .setFontSize(13)
                    .setBold()
                    .setFontColor(new DeviceRgb(30, 40, 60))
                    .setMarginBottom(10));

            // ── Data table ────────────────────────────────────────────────────
            Table table = new Table(UnitValue.createPercentArray(new float[] { 50, 50 }))
                    .useAllAvailableWidth()
                    .setMarginBottom(24);

            // Column headers
            table.addHeaderCell(styledHeaderCell("Metric"));
            table.addHeaderCell(styledHeaderCell("Value"));

            // Data rows
            boolean alternate = false;
            for (Map.Entry<String, String> entry : data.entrySet()) {
                DeviceRgb bg = alternate ? ROW_ALT : new DeviceRgb(255, 255, 255);
                table.addCell(styledDataCell(entry.getKey(), bg, false));
                table.addCell(styledDataCell(entry.getValue(), bg, true));
                alternate = !alternate;
            }
            doc.add(table);

            // ── Footer ────────────────────────────────────────────────────────
            doc.add(new Paragraph(
                    "This report was automatically generated by PortSight Analytics. " +
                            "Values are based on simulated market data for demonstration purposes.")
                    .setFontSize(8)
                    .setFontColor(new DeviceRgb(160, 170, 185))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(30));

            doc.close();
            return baos.toByteArray();

        } catch (Exception e) {
            log.error("PDF generation failed for reportType={}: {}", reportType, e.getMessage(), e);
            throw new RuntimeException("PDF generation failed: " + e.getMessage(), e);
        }
    }

    private Cell styledHeaderCell(String text) {
        return new Cell()
                .setBackgroundColor(new DeviceRgb(30, 40, 60))
                .setPadding(8)
                .setBorder(null)
                .add(new Paragraph(text)
                        .setFontColor(ColorConstants.WHITE)
                        .setFontSize(10)
                        .setBold());
    }

    private Cell styledDataCell(String text, DeviceRgb bg, boolean rightAlign) {
        return new Cell()
                .setBackgroundColor(bg)
                .setPadding(7)
                .setBorder(null)
                .add(new Paragraph(text)
                        .setFontSize(10)
                        .setFontColor(new DeviceRgb(30, 40, 60))
                        .setTextAlignment(rightAlign ? TextAlignment.RIGHT : TextAlignment.LEFT));
    }

    private String formatReportTitle(String type) {
        return switch (type.toUpperCase()) {
            case "PORTFOLIO" -> "Portfolio";
            case "RISK" -> "Risk";
            case "PERFORMANCE" -> "Performance";
            case "ALLOCATION" -> "Allocation";
            default -> type;
        };
    }
}